package com.ipoondev.android.psugo.utilities

const val EXTRA_SETTINGS = "Settings"
const val EXTRA_TRANSITION_ENTER = "EXTRA_TRANSITION_ENTER"

const val PERMISSION_REQUEST_FINE_LOCATION = 111


// Broadcast Constant
const val BROADCAST_REGISTER_GEOFENCE_COMPLELE = "BROADCAST_REGISTER_GEOFENCE_COMPLELE"
const val BROADCAST_GEOFENCE_TRANSITION_ENTER = "BROADCAST_GEOFENCE_TRANSITION_ENTER"
const val BROADCAST_GEOFENCE_TRANSITION_EXIT = "BROADCAST_GEOFENCE_TRANSITION_EXIT"
